### ISSUE TITLE
Where to buy RetroWave OPL3 inside China?

### ISSUE THREAD

**Issue by crazii** [SudoMaker/RetroWave#3]
国内在哪里可以买到RetroWave OPL3呢? win98需要驱动吗？
抱歉因为github没有PM了， 只能在这里提issue
在b站看到这个东西很神奇，而且发现是国内的，我的马，有点小激动

**Comment by ClassicOldSong** [comment]
Hi there,

First of all please use English to submit an issue in a global oriented project. Since you might not want to read any other languages you don't understand, others may feel the same. It is a matter of respect to all other people around the world.

To answer your question, we're now having issues with Tindie and will open a independent online store shortly. There's currently no way of purchasing this product directly due to the chip shortage. We've made an alternative board to compensate for the missing part, but there's not much left. You may find our store on Taobao by searching "SudoMaker", and we might be able to arrange a spare one for you if there're still some left.

Since this is not an issue related directly to this project itself, I'm closing this issue now. You may contact us by this email: yukino@sudomaker.com .

Regards,
Yukino Song
